import Learn from "../components/learn";

const cards = [
  {
    question: "a challenge",
    answer: "un desafío/reto",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 0,
  },
  {
    question: "the helmet",
    answer: "el casco",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 1,
  },
  {
    question: "fishing rod",
    answer: "la caña",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 2,
  },
  {
    question: "bait",
    answer: "la carnada",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 3,
  },
  {
    question: "scooter/skateboard",
    answer: "la patineta",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 4,
  },
  {
    question: "knee pad",
    answer: "la rodillera",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 5,
  },
  {
    question: "elbow brace",
    answer: "la codera",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 6,
  },
  {
    question: "surfboard",
    answer: "la tabla de surf",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 7,
  },
  {
    question: "snowboard",
    answer: "la tabla de nieve",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 8,
  },
  {
    question: "wave",
    answer: "la ola",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 9,
  },
  {
    question: "training/practice session",
    answer: "el entrenamiento",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 10,
  },
  {
    question: "diving board",
    answer: "el trampolín",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 11,
  },
  {
    question: "platform",
    answer: "la plataforma",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 12,
  },
  {
    question: "tie (game)",
    answer: "el empate",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 13,
  },
  {
    question: "to train",
    answer: "entrenar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 14,
  },
  {
    question: "to make an effort",
    answer: "esforzarse",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 15,
  },
  {
    question: "to come in 1st/2nd/3rd place",
    answer: "salir en primer/segundo/tercer lugar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 16,
  },
  {
    question: " campeona",
    answer: "salir campeón",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 17,
  },
  {
    question: "to take place",
    answer: "tener lugar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 18,
  },
  {
    question: "slide",
    answer: "deslizarse",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 19,
  },
  {
    question: "to hold",
    answer: "sujetar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 20,
  },
  {
    question: "to have a good/bad time",
    answer: "pasarlo bien/mal",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 21,
  },
  {
    question: "I had a good/bad time",
    answer: "Lo pasé bien/mal",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 22,
  },
  {
    question: "to achieve",
    answer: "lograr/alcanzar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 23,
  },
  {
    question: "to fish",
    answer: "pescar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 24,
  },
  {
    question: "to go skateboarding/scootering",
    answer: "andar en patineta",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 25,
  },
  {
    question: "to surf",
    answer: "surfear",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 26,
  },
  {
    question: "to throw",
    answer: "lanzar/tirar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 27,
  },
  {
    question: "to grab",
    answer: "agarrar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 28,
  },
  {
    question: "to take a walk",
    answer: "dar una vuelta",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 29,
  },
  {
    question: "to defeat",
    answer: "vencer",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 30,
  },
  {
    question: "to climb",
    answer: "escalar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 31,
  },
  {
    question: "to go up",
    answer: "subir",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 32,
  },
  {
    question: "to go down",
    answer: "bajar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 33,
  },
  {
    question: "to advance",
    answer: "adelantar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 34,
  },
  {
    question: "to advance",
    answer: "avanzar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 35,
  },
  {
    question: "to score points",
    answer: "hacer puntos",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 36,
  },
  {
    question: "court",
    answer: "la cancha",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 37,
  },
  {
    question: "track",
    answer: "la pista",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 38,
  },
  {
    question: "trophy",
    answer: "el trofeo",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 39,
  },
  {
    question: "gold/silver/bronze medal",
    answer: "la medalla de oro/plata/bronce",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 40,
  },
  {
    question: "first/second place",
    answer: "primer/segundo lugar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 41,
  },
  {
    question: "board game",
    answer: "el juego de mesa",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 42,
  },
  {
    question: "checkers",
    answer: "las damas",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 43,
  },
  {
    question: "darts",
    answer: "los dardos",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 44,
  },
  {
    question: "dominoes",
    answer: "el dominó",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 45,
  },
  {
    question: "table soccer (foosball)",
    answer: "el futbolín",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 46,
  },
  {
    question: "air hockey",
    answer: "el hockey de aire",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 47,
  },
  {
    question: "billiards",
    answer: "el billar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 48,
  },
  {
    question: "ping pong",
    answer: "el pimpón",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 49,
  },
  {
    question: "board",
    answer: "el tablero",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 50,
  },
  {
    question: "dice",
    answer: "los dados",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 51,
  },
  {
    question: "game piece",
    answer: "la ficha",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 52,
  },
  {
    question: "videogame console",
    answer: "la consola de videojuegos",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 53,
  },
  {
    question: "skill",
    answer: "la destreza",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 54,
  },
  {
    question: "to move (oneself)",
    answer: "moverse (o-ue)",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 55,
  },
  {
    question: "to throw",
    answer: "tirar",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 56,
  },
  {
    question: "kite",
    answer: "la cometa",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 57,
  },
  {
    question: "harness",
    answer: "el arnés",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 58,
  },
  {
    question: "mountain climbing",
    answer: "el alpinismo",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 59,
  },
  {
    question: "rock climbing",
    answer: "la escalada deportiva",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 60,
  },
  {
    question: "snorkeling",
    answer: "el esnórquel",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 61,
  },
  {
    question: "water sport",
    answer: "el deporte acuático",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 62,
  },
  {
    question: "kitesurfing",
    answer: "el kitesurf",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 63,
  },
  {
    question: "windsurfing",
    answer: "el surf a vela",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 64,
  },
  {
    question: "cycle track",
    answer: "el velódromo",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 65,
  },
  {
    question: "club/stick",
    answer: "el palo",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 66,
  },
  {
    question: "glove",
    answer: "el guante",
    correct: null,
    userAnswer: null,
    learnStatus: 0,
    id: 67,
  },
];

const LearnMode = () => {
  return <Learn cards={cards} />;
};

export default LearnMode;
